// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGFrYAEFL2G0PflsoocHvqn4CZ3-YEdG4',
    appId: '1:283250472851:web:208de93930e64556e71a66',
    messagingSenderId: '283250472851',
    projectId: 'test-loggin-efd21',
    authDomain: 'test-loggin-efd21.firebaseapp.com',
    storageBucket: 'test-loggin-efd21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVd-mRKX2G0S2H-Fem903dhc7g6_rvqTw',
    appId: '1:283250472851:android:5426ed6d27b7ca2be71a66',
    messagingSenderId: '283250472851',
    projectId: 'test-loggin-efd21',
    storageBucket: 'test-loggin-efd21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfPqNWVbMolKrGYJmH1sTIzxWT9eeF3UI',
    appId: '1:283250472851:ios:30ce6519b7314516e71a66',
    messagingSenderId: '283250472851',
    projectId: 'test-loggin-efd21',
    storageBucket: 'test-loggin-efd21.firebasestorage.app',
    iosBundleId: 'com.example.examenU2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfPqNWVbMolKrGYJmH1sTIzxWT9eeF3UI',
    appId: '1:283250472851:ios:30ce6519b7314516e71a66',
    messagingSenderId: '283250472851',
    projectId: 'test-loggin-efd21',
    storageBucket: 'test-loggin-efd21.firebasestorage.app',
    iosBundleId: 'com.example.examenU2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGFrYAEFL2G0PflsoocHvqn4CZ3-YEdG4',
    appId: '1:283250472851:web:03c1ecac0a783f1ae71a66',
    messagingSenderId: '283250472851',
    projectId: 'test-loggin-efd21',
    authDomain: 'test-loggin-efd21.firebaseapp.com',
    storageBucket: 'test-loggin-efd21.firebasestorage.app',
  );
}
